/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blackjack;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.Icon;
import java.lang.Object;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class interfaceBlackjack extends javax.swing.JFrame {

    /**
     * Creates new form interfaceBlackjack
     */
    
    private Jogador player;

    public interfaceBlackjack() {
        initComponents();
        somatorio_player = carta1.getValor_carta()+carta2.getValor_carta();
        somatorio_mesa = carta_mesa1.getValor_carta()+carta_mesa2.getValor_carta();
        caixa_total_apostado.setText("0");
        carta_mesa1.mostrar_valor();
        carta1.mostrar_valor();
        carta2.mostrar_valor();
        /*carta8.setVisible(true);
        carta7.setVisible(false);
        carta6.setVisible(false);
        carta5.setVisible(false);
        carta4.setVisible(false);   
        carta3.setVisible(false);*/
        player = new Jogador();
        atualizar_saldo(player);
    }
    void atualizar_saldo(Jogador player){
        caixa_saldo.setText('$'+Integer.toString(player.getSaldo()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Painel_cartas_mesa = new javax.swing.JPanel();
        carta_mesa1 = new blackjack.Carta();
        carta_mesa2 = new blackjack.Carta();
        Painel_cartas_jogador = new javax.swing.JPanel();
        carta1 = new blackjack.Carta();
        carta2 = new blackjack.Carta();
        carta3 = new blackjack.Carta();
        carta4 = new blackjack.Carta();
        carta5 = new blackjack.Carta();
        carta6 = new blackjack.Carta();
        carta7 = new blackjack.Carta();
        carta8 = new blackjack.Carta();
        caixa_saldo = new javax.swing.JTextField();
        take_a_card_button = new javax.swing.JButton();
        stay_button = new javax.swing.JButton();
        botao_aposta = new javax.swing.JButton();
        botao_surrender = new javax.swing.JButton();
        caixa_apostar = new javax.swing.JTextField();
        caixa_total_apostado = new javax.swing.JTextField();
        texto_totalApostado = new javax.swing.JLabel();
        texto_saldo = new javax.swing.JLabel();
        double_button = new javax.swing.JButton();
        background_mesa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JackPreto");

        jPanel1.setLayout(null);

        Painel_cartas_mesa.setLayout(new javax.swing.BoxLayout(Painel_cartas_mesa, javax.swing.BoxLayout.LINE_AXIS));
        Painel_cartas_mesa.add(carta_mesa1);
        Painel_cartas_mesa.add(carta_mesa2);

        jPanel1.add(Painel_cartas_mesa);
        Painel_cartas_mesa.setBounds(500, 200, 150, 97);

        Painel_cartas_jogador.setBackground(new java.awt.Color(188, 78, 43));
        Painel_cartas_jogador.setLayout(new javax.swing.BoxLayout(Painel_cartas_jogador, javax.swing.BoxLayout.LINE_AXIS));
        Painel_cartas_jogador.add(carta1);
        Painel_cartas_jogador.add(carta2);
        Painel_cartas_jogador.add(carta3);
        Painel_cartas_jogador.add(carta4);
        Painel_cartas_jogador.add(carta5);
        Painel_cartas_jogador.add(carta6);
        Painel_cartas_jogador.add(carta7);
        Painel_cartas_jogador.add(carta8);

        jPanel1.add(Painel_cartas_jogador);
        Painel_cartas_jogador.setBounds(280, 490, 584, 100);

        caixa_saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixa_saldoActionPerformed(evt);
            }
        });
        jPanel1.add(caixa_saldo);
        caixa_saldo.setBounds(100, 10, 80, 29);

        take_a_card_button.setText("Take a Card");
        take_a_card_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                take_a_card_buttonMouseClicked(evt);
            }
        });
        take_a_card_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                take_a_card_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(take_a_card_button);
        take_a_card_button.setBounds(930, 490, 140, 31);

        stay_button.setText("Stay");
        stay_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stay_buttonMouseClicked(evt);
            }
        });
        stay_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stay_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(stay_button);
        stay_button.setBounds(30, 590, 90, 31);

        botao_aposta.setText("Aposta");
        botao_aposta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_apostaMouseClicked(evt);
            }
        });
        botao_aposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_apostaActionPerformed(evt);
            }
        });
        jPanel1.add(botao_aposta);
        botao_aposta.setBounds(30, 510, 90, 30);

        botao_surrender.setText("Surrender");
        botao_surrender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_surrenderMouseClicked(evt);
            }
        });
        botao_surrender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_surrenderActionPerformed(evt);
            }
        });
        jPanel1.add(botao_surrender);
        botao_surrender.setBounds(930, 560, 150, 31);

        caixa_apostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixa_apostarActionPerformed(evt);
            }
        });
        jPanel1.add(caixa_apostar);
        caixa_apostar.setBounds(130, 509, 70, 30);
        jPanel1.add(caixa_total_apostado);
        caixa_total_apostado.setBounds(420, 310, 130, 29);

        texto_totalApostado.setForeground(new java.awt.Color(255, 0, 0));
        texto_totalApostado.setText("Total Apostado");
        jPanel1.add(texto_totalApostado);
        texto_totalApostado.setBounds(310, 310, 110, 30);

        texto_saldo.setForeground(new java.awt.Color(255, 0, 0));
        texto_saldo.setText("SALDO");
        jPanel1.add(texto_saldo);
        texto_saldo.setBounds(40, 10, 60, 30);

        double_button.setText("Double");
        double_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                double_buttonMouseClicked(evt);
            }
        });
        double_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                double_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(double_button);
        double_button.setBounds(30, 550, 90, 31);

        background_mesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table.png"))); // NOI18N
        jPanel1.add(background_mesa);
        background_mesa.setBounds(-20, 0, 1140, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1138, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void double_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_double_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_double_buttonActionPerformed

    private void take_a_card_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_take_a_card_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_take_a_card_buttonActionPerformed

    private void stay_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stay_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stay_buttonActionPerformed

    private void botao_surrenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_surrenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_surrenderActionPerformed

    private void botao_apostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_apostaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_apostaActionPerformed

    private void take_a_card_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_take_a_card_buttonMouseClicked
        // TODO add your handling code here:
        if(!evt.isMetaDown()){
            if(!carta3.esta_aberto()){
                carta3.mostrar_valor();
                somatorio_player+=carta3.getValor_carta();
                System.out.println(somatorio_player);
            }else
            if(!carta4.esta_aberto()){
                carta4.mostrar_valor();
                somatorio_player+=carta4.getValor_carta();
                System.out.println(somatorio_player);
            }else
            if(!carta5.esta_aberto()){
                carta5.mostrar_valor();
                somatorio_player+=carta5.getValor_carta();
                System.out.println(somatorio_player);
            }else
            if(!carta6.esta_aberto()){
                carta6.mostrar_valor();
                somatorio_player+=carta6.getValor_carta();
                System.out.println(somatorio_player);
            }else
            if(!carta7.esta_aberto()){
                carta7.mostrar_valor();
                somatorio_player+=carta7.getValor_carta();
                System.out.println(somatorio_player);
            }else 
            if(!carta8.esta_aberto()){
                carta8.mostrar_valor();
                somatorio_player+=carta8.getValor_carta();
                System.out.println(somatorio_player);
            }
        }
    }//GEN-LAST:event_take_a_card_buttonMouseClicked

    private void caixa_saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixa_saldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixa_saldoActionPerformed

    private void caixa_apostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixa_apostarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixa_apostarActionPerformed
    
    private void atualiza_caixa_quantidade_apostada(){
        caixa_total_apostado.setText(Integer.toString(player.getQuantidade_apostada()));
    }
    private void atualiza_caixa_saldo(){
        caixa_saldo.setText(Integer.toString(player.getSaldo()));
    }
    int somatorio_player;
    int somatorio_mesa;
    //////////////////
    //LOGICA GAME/////
    ///////////////////
    private void verifica_quem_ganhou(){
        
        if(verifica_se_estourou() || somatorio_player < somatorio_mesa){
            //JANELA PERDEU MAI BRUDA
            System.out.println("VOCE PERDEU");
        }else
        if(somatorio_player > somatorio_mesa){
            //JANELA VOCE GANHOU MAI BRUDA
            System.out.println("VOCE GANHOU");
            player.setSaldo(player.getQuantidade_apostada()*2);
        }else if(somatorio_player == somatorio_mesa){
            //JANELA EMPATOU
            System.out.println("VOCE EMPATOU");
            player.atualizar_saldo(player.getQuantidade_apostada());
        }
        reinicia_game();
    }
    private boolean verifica_se_estourou(){
        
        return (somatorio_player > 21);

    }
    private void reinicia_game(){
        player.setQuantidade_apostada(0);
        atualiza_caixa_quantidade_apostada();
        carta1.carta_random();
        carta2.carta_random();
        carta3.carta_random();
        carta4.carta_random();
        carta5.carta_random();
        carta6.carta_random();
        carta7.carta_random();
        carta8.carta_random();
        carta1.mostrar_valor();
        carta2.mostrar_valor();
        
        carta_mesa1.carta_random();
        carta_mesa2.carta_random();
        carta_mesa1.mostrar_valor();
        
    }
    private void botao_apostaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_apostaMouseClicked
        // TODO add your handling code here:
        if(!evt.isMetaDown()){
           int aux = Integer.parseInt(caixa_apostar.getText());
           player.somar_aposta(aux);
           player.atualizar_saldo(aux*-1);
           atualiza_caixa_quantidade_apostada();
           atualiza_caixa_saldo();
           caixa_apostar.setText("0");

           
        }
    }//GEN-LAST:event_botao_apostaMouseClicked

    private void double_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_double_buttonMouseClicked
        // TODO add your handling code here:
        int aux =player.quantidade_apostada;
        player.somar_aposta(aux);
        player.atualizar_saldo(aux*-1);
        atualiza_caixa_quantidade_apostada();
        atualiza_caixa_saldo();
    }//GEN-LAST:event_double_buttonMouseClicked

    private void botao_surrenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_surrenderMouseClicked
        // TODO add your handling code here:
        int aux =player.quantidade_apostada/2;
        player.somar_aposta(aux*-1);
        player.atualizar_saldo(aux);
        atualiza_caixa_quantidade_apostada();
        atualiza_caixa_saldo();
        reinicia_game();
    }//GEN-LAST:event_botao_surrenderMouseClicked

    private void stay_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stay_buttonMouseClicked
        // TODO add your handling code here:
        verifica_quem_ganhou();
        carta_mesa2.mostrar_valor();
    }//GEN-LAST:event_stay_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaceBlackjack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaceBlackjack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaceBlackjack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaceBlackjack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaceBlackjack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel_cartas_jogador;
    private javax.swing.JPanel Painel_cartas_mesa;
    private javax.swing.JLabel background_mesa;
    private javax.swing.JButton botao_aposta;
    private javax.swing.JButton botao_surrender;
    private javax.swing.JTextField caixa_apostar;
    private javax.swing.JTextField caixa_saldo;
    private javax.swing.JTextField caixa_total_apostado;
    private blackjack.Carta carta1;
    private blackjack.Carta carta2;
    private blackjack.Carta carta3;
    private blackjack.Carta carta4;
    private blackjack.Carta carta5;
    private blackjack.Carta carta6;
    private blackjack.Carta carta7;
    private blackjack.Carta carta8;
    private blackjack.Carta carta_mesa1;
    private blackjack.Carta carta_mesa2;
    private javax.swing.JButton double_button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton stay_button;
    private javax.swing.JButton take_a_card_button;
    private javax.swing.JLabel texto_saldo;
    private javax.swing.JLabel texto_totalApostado;
    // End of variables declaration//GEN-END:variables
}
